server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${sky.datasource.driver-class-name}
    url: jdbc:mysql://localhost:3306/game_web
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}
  servlet:
    multipart:
      #配置文件上传的最大大小
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    password: ${sky.redis.password}
    database: ${sky.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.itmy.pojo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

aliyun:
  oss:
    endpoint: ${sky.aliyun.oss.endpoint}
    bucketName: ${sky.aliyun.oss.bucketName}
    region: ${sky.aliyun.oss.region}

alipay:
  easy:
    protocol: https
    gatewayHost: openapi-sandbox.dl.alipaydev.com
    signType: RSA2
    appId: 9021000164663471
    merchantPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCOreLExm8RniP5EbFtjsA+qPC9CPD4pYVD4TB5KOBOpDipFbDpf9o7KBHOFS+Ix+Lg4kME0Pa3+DPZJ6obht+zrw0FLEWvE9DuH9fAgSgo/flfuwd1hKZsUgzFxtMbsUmHcr7hGNfd1DhjbuEw+C7GSSyOCnk4pzFpT6t3XwzfyHdDeGwIckydAL1CQ4Ic7EflG25x8dH7QdTDYTuhI96u+m7iXZwP8H35U7scZa+bg2vYHHVXbz5+9rFK15ymvvqSxSFNM7603axZPGmXZ7AXJ0DbreNTv9lhWm3L9K3Df0oeL/lcJMpM/Ubq5wl25yMuvG3BrBoi3Ny+oEfouABnAgMBAAECggEAFdB4L2W3bZYkIdyWqA1/TxU9WWmYjiugaHRxmNSrFtr83r02Qz0M/KZvsnaCwgLtqTxuyrm4PwBvzO/HjlXctfg5oWTXcqEw/HdZ4VDd9wZ9rilGRq11VHJnCYYQmNdOSqs8i+Xke0ILLQiy3W3UmPRvH3hyeDr3zwYjTSj3Ku+bmzSLZbyAGWgBpuWdy2Zf2yyu3x4BypHnI9j7ulX16zSgZ/9kPawU04cRnNJSpp13tD3rQGzZH8dxFi7oj4FR0mbeDHdYlRg+q1LQx/Hy5frw+jygiFOeknpNu2HdYptmtcpx22faw/1nwdo2RQOf03JuR/maESDPF5pn9ZaFgQKBgQDtVq+ssvT5rRG6Tx7pl/k0NRqnW+ZYKm80pwKmyoiTq+vB3/XpD8kY+DKlxF9YUsgRqtbf+3XpOOlOMFqLiC1scrH6X6SO2FjbCdJqKHeVuJpb40puCSY9L3br9tcqZPskVxyCppFXqM+IgtWTIbmCpld/6J3NUjiFaArfBud+kQKBgQCZ5dS9b6d73nSa8VJ2xNFE5/4RfVeWnsE1X7aVKYva36HzGYGmm5XN3foD+TBbWRSCgBxpWvMPQO2VCR2Ly299eXp11wpod20dQKjylp9Lu0wG3n31UXF5s41z/jVOHP0dD4DSbwRrsizUmhf/6GTKjxTdo7Z2PJbYgMCMI8T7dwKBgC5ReptjmXeYlRsdEdVYuWO88WS0BLI0JdvKtDPE1v6q0KnXgXBoikB7P7cmKc1c6nq4MpMnyg0n9DA0M5eDjgnaIG3SeJUAF+c3dX8OQrhPfKBuLTpoQrQyLS1D0R4O8wxWi9PbmgXXhhkIH5JFRKUAvZbS2OkXILy4X1bDTC5hAoGACWI2IobYU3kw6vGj8ZH2oJj0qORXntt3NGXtoBK0cFgKa+Q2P45lB/Rs9ikPhcJcuchN8y6Ue22eDuRLZOa2mZP6n4zJGa2OfaYfpwsAE4IMFK8kRvz8SktkaJorbePemxMC69HRFy/6A8yRgg0NeDxZLVp6GaOAHxtaojDcJekCgYARMle9vsQBjF+bOHegq3EwVLYdxHTk8Npa0S7ycBBKl1wJZRMx2HknSW6xSjZi8NRbPaWsZryykOEpKHzXofMVusYRCFCjITjkzoKT1oqIWfExZmfgQZqcJ23OL8ce6kFR+qWfrZzgi6C1ahRrZDOA+eU/APxjwAXGDeIUoERFTA==
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlH4mk97Sf0KxwC9qZw4LDajtbsG2dmqlHZcQUg3o2dtFTOkWvh2QzNzvE3Oo32uxTJ4SOJrwIqpdlNVAH3Fcc72YZQ54/P6qkP8W/6uazvlzMcNPshwo5DH28CImDMCQg1tUOdf5EK75bcmBT3pjp/D9AuMKmabxRlGmMSjX78wKcTnRpz21slmVadjzTLxZO3aZgqK6BMhxhKWF2LJngDi6MCasX0FEYeXXt6zKttkbDFL5s5J0KGNzWLxeiCh7piYEOlzhyd8Uxj2RlEH06lypYAFESSUh70HpOqFQlUbAJ3KJ6ndICFqQsCsDyx0MQuggpEg6+bXRTjjUH9jlBQIDAQAB
    notifyUrl: https://1922b808.r10.vip.cpolar.cn/notify